In [3]:
#1. Write a Numpy program to get the Numpy version 
# and show the Numpy build configuration.

import numpy as np
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anacond

In [ ]:
# 2. Write a NumPy program 
# to get help with the add function.

In [8]:
import numpy as np
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [16]:
#3. Write a NumPy program to test whether
# none of the elements of a given array are zero.

import numpy as np
a =np.array([1,2,3,4])
print("Original array:")
print(a)

print("The elements in array is zero :")
print(np.all(a))
a = np.array([0,1,2,3,4])
print("Original array :")
print(a)
print("The elements in array is zero :")
print(np.all(a))

Original array:
[1 2 3 4]
The elements in array is zero :
True
Original array :
[0 1 2 3 4]
The elements in array is zero :
False


In [19]:
# 4. Write a NumPy program to test 
# if any of the elements of a given array are non-zero. 

In [23]:
import numpy as np
c = np.array([1,2,3,0,0,0,])
print("Original arraay :")
print(c)
print("The elements of a given is non zero :")
print(np.any(c))
c = np.array([0,0,0,0])
print("Original array :")
print(c)
print("The elements in array is non zero :")
print(np.any(c))


Original arraay :
[1 2 3 0 0 0]
The elements of a given is non zero :
True
Original array :
[0 0 0 0]
The elements in array is non zero :
False


In [24]:
#  5. Write a NumPy program to test a given array
# element-wise for finiteness (not infinity or not a number).

import numpy as np
a = np.array([1,2,0,np.nan,np.inf])
print("Original array")
print(a)
print("Given array element-wise for finiteness :")
print(np.isfinite(a))





Original array
[ 1.  2.  0. nan inf]
Given array element-wise for finiteness :
[ True  True  True False False]


In [38]:
# 6. Write a NumPy program to test elements-wise 
# for positive or negative infinity.

import numpy as np

