# Numpy vs lists

In [3]:
#lets define a list in python.
heights = [20,45,67,87,66]
print(type(heights))

<class 'list'>


In [5]:
#multiply with 2.54
#heights * 2
h1=[]
for i in heights:
    h1.append(i*2.54)
print(h1)
    

[50.8, 114.3, 170.18, 220.98, 167.64000000000001]


In [8]:
#try to multiple heights with scalar.
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [9]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
heights =[20,45,67,87,66]
np.heights = np.array(heights)
print(np.heights)

[20 45 67 87 66]


In [12]:
np.heights = np.array([20,45, 67, 87, 66])
print(np.heights)

[20 45 67 87 66]


In [13]:
type(np.heights)

numpy.ndarray

In [14]:
h1

[50.8, 114.3, 170.18, 220.98, 167.64000000000001]

In [15]:
np.heights*2.54

array([ 50.8 , 114.3 , 170.18, 220.98, 167.64])

In [18]:
#define a numpy array
#also print the type of numpy array
np_heights = np.array(heights)
print(type(np_heights))

<class 'numpy.ndarray'>


In [19]:
#multiple height (numpy array) with scalar.
np_heights*2.54

array([ 50.8 , 114.3 , 170.18, 220.98, 167.64])

# Numpy comes with its own set of methods and operations

In [20]:
#lets define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 =[4,5]
list_3 = list_1 + list_2
print(list_3)

[1, 2, 3, 4, 5]


In [22]:
#lets define two numpy array anfd perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2


array([5, 7, 9])

In [23]:
type(np1)

numpy.ndarray

# Working with N-D Arrays

In [24]:
np_heights

array([20, 45, 67, 87, 66])

In [27]:
type(np_heights)

numpy.ndarray