In [4]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
6
int32


In [ ]:
#zeros function uses to print only '0' elements.
a = np.zeros((4,5)) # here we given 4 rows and 5 columns.

In [5]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
b = np.full((3,3),2,dtype = float)  #Here we given diof arrrays 3x3 and 
                                   #valve is 2 which we want in float.
print(b)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [20]:
#it prints any of random numbers.
c = np.random.random((2,3))
print(c)

[[0.20878036 0.94704773 0.85548303]
 [0.26810665 0.73925015 0.53096084]]


In [21]:
d = np.arange(0,30,5)
print(d)

[ 0  5 10 15 20 25]


In [22]:
e = np.linspace(0,5,10)
print(e)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
f = np.arr